---
- name: Import the security@parity.io GPG key
  ansible.builtin.shell: |
    sudo gpg --recv-keys --keyserver hkps://keys.mailvelope.com 9D4B2B6EB8F97156D19669A9FF0812D491B96798
    set -o pipefail && sudo gpg --export 9D4B2B6EB8F97156D19669A9FF0812D491B96798 |
    sudo tee /usr/share/keyrings/parity.gpg
  changed_when: false

- name: Add the Parity repository and update the package index
  ansible.builtin.shell: |
    set -o pipefail && echo 'deb [signed-by=/usr/share/keyrings/parity.gpg] https://releases.parity.io/deb release main' |
    sudo tee /etc/apt/sources.list.d/parity.list
    sudo apt update
  changed_when: false

- name: Install the `parity-keyring` package to ensure that the GPG key used by apt remains up-to-date
  ansible.builtin.command: sudo apt install parity-keyring
  changed_when: false

- name: Install Polkadot
  ansible.builtin.command: sudo apt install polkadot
  changed_when: false

- name: Add user "ansibleuser" to sudo
  ansible.builtin.lineinfile:
  path: /etc/sudoers.d/ansibl_sudoers
  line: 'polkadot ALL=(ALL) NOPASSWD: ALL'
  state: present
  mode: 0440
  create: yes
  validate: 'visudo -cf %s'

- name: Create Polkadot systemd service file
  ansible.builtin.template:
    src: polkadot.service
    dest: /etc/systemd/system/polkadot.service
    owner: polkadot
    group: polkadot
    mode: 0600
  become: true
  changed_when: false

- name: Create Parachain data directory
  ansible.builtin.file:
    path: /mnt/disks/data/chains/polkadot/db/full
    state: directory
    mode: 0755
    owner: polkadot
    group: polkadot
  become: true
  changed_when: false

- name: Create Relay data directory
  ansible.builtin.file:
    path: /mnt/disks/data/chains/kusama/db/full
    state: directory
    mode: 0755
    owner: polkadot
    group: polkadot
  become: true
  changed_when: false

- name: Enable Polkadot systemd service
  ansible.builtin.command: sudo systemctl enable polkadot
  changed_when: false
