---
- name: Import the security@parity.io GPG key
  ansible.builtin.shell: |
    sudo gpg --recv-keys --keyserver hkps://keys.mailvelope.com 9D4B2B6EB8F97156D19669A9FF0812D491B96798
    set -o pipefail && sudo gpg --export 9D4B2B6EB8F97156D19669A9FF0812D491B96798 |
    sudo tee /usr/share/keyrings/parity.gpg
  changed_when: false

- name: Add the Parity repository and update the package index
  ansible.builtin.shell: |
    set -o pipefail && echo 'deb [signed-by=/usr/share/keyrings/parity.gpg] https://releases.parity.io/deb release main' |
    sudo tee /etc/apt/sources.list.d/parity.list
    sudo apt update
  changed_when: false

- name: Install `parity-keyring` package, Polkadot and extraction tools
  ansible.builtin.apt:
    pkg:
      - parity-keyring
      - polkadot
      #- liblz4-tool
  become: true

- name: Add polkadot user to sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ansible_sudoers
    line: "polkadot ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: true
    validate: "visudo -cf %s"
    backup: true
  become: true
  changed_when: false

- name: Create Polkadot systemd service file
  ansible.builtin.template:
    src: polkadot.service
    dest: /etc/systemd/system/polkadot.service
    owner: polkadot
    group: polkadot
    mode: 0600
  become: true
  changed_when: false

- name: Create Parachain data directory
  ansible.builtin.file:
    path: /mnt/disks/data/chains/polkadot
    state: directory
    mode: 0755
    owner: polkadot
    group: polkadot
  become: true
  changed_when: false

- name: Create Relay data directory
  ansible.builtin.file:
    path: /mnt/disks/data/chains/kusama
    state: directory
    mode: 0755
    owner: polkadot
    group: polkadot
  become: true
  changed_when: false

# - name: Download Polkadot data snapshot from Polkashots
#   ansible.builtin.shell: |
#     set -o pipefail && sudo curl -o - -L https://dot-rocksdb.polkashots.io/snapshot |
#     lz4 -c -d - |
#     tar -x -C /mnt/disks/data/chains/polkadot
#   changed_when: false

# - name: Download Kusama data snapshot from Polkashots
#   ansible.builtin.shell: |
#     set -o pipefail && curl -o - -L https://ksm-rocksdb.polkashots.io/snapshot |
#     lz4 -c -d - |
#     tar -x -C /mnt/disks/data/chains/kusama
#   changed_when: false

- name: Enable Polkadot systemd service
  ansible.builtin.command: sudo systemctl enable polkadot
  changed_when: false
