name: Provision Nodes

on:
  push:
    branches: 
      - main

jobs:
  run:
    name: 'Setup GCP provision nodes'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: '${ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }'
          service_account: '${ secrets.TERRAFORM_SERVICE_ACCOUNT_EMAIL }'
          project_id: '${ secrets.GCP_PROJECT_ID }'
          audience: '${ secrets.GCP_POOL_AUDIENCE }'
          token_format: 'access_token'
          access_token_lifetime: '1800' # 30 minutes

      - name: Install Polkadot
        uses: tomasnorre/ansible-cli-client@v0.0.7
        with:
          command: 'cd ansible && ansible-playbook -i inventory/hosts.ini playbook.yml && cd ..'
