name: Provision Nodes

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    branches: 
      - main
    types: 
      - completed

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"

  run:
    name: 'Provision Nodes'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: [ validate ]
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.TERRAFORM_SERVICE_ACCOUNT_EMAIL }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Make Credentials file more secure
        run: chmod 400 "${{ steps.auth-gcp.outputs.credentials_file_path }}"
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

      - name: Install Polkadot
        run: cd ansible && ansible-playbook playbook.yml --key-file "${{ steps.auth-gcp.outputs.credentials_file_path }}" && cd ..
