name: Provision Nodes

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    branches: 
      - main
    types: 
      - completed

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"

  run:
    name: 'Provision Nodes'
    runs-on: ubuntu-latest
    needs: [ validate ]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

      - name: Make Credentials file more secure
        run: chmod 400 ansible/.ssh/id_rsa.pub

      - name: Install Polkadot
        run: cd ansible && ansible-playbook playbook.yml --key-file ".ssh/id_rsa.pub" && cd ..
