name: Provision Nodes

on:
  workflow_run:
    workflows: ["Deploy self-hosted actions runner"]
    branches: [main]
    types: 
      - completed

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"

  run-playbook:
    runs-on: ubuntu-latest
		needs: [ validate ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

      - name: write inventory to file
      env:
        INVENTORY: ${{ secrets.INVENTORY }}
      run: 'echo "$INVENTORY" > ../ansible/inventory/hosts.ini'

      - name: Authenticate to Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.TERRAFORM_SERVICE_ACCOUNT_EMAIL }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          audience: '${{ secrets.GCP_POOL_AUDIENCE }}'
          token_format: 'access_token'
          access_token_lifetime: '1800' # 30 minutes

      - name: run playbook
        run: ansible-playbook -i inventory inventory/hosts.ini
