name: Deploy self-hosted actions runner

on:
  push:
    branches: 
      - main

jobs:
  run:
    name: 'Setup GCP and Deploy self-hosted actions runner'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - run: |
        echo '${ secrets.TERRAFORM_SERVICE_ACCOUNT_EMAIL }'

      - name: Authenticate to Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: '${ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }'
          service_account: '${ secrets.TERRAFORM_SERVICE_ACCOUNT_EMAIL }'
          project_id: '${ secrets.GCP_PROJECT_ID }'
          token_format: 'access_token'
          audience: '${ secrets.GCP_POOL_AUDIENCE }'

      - name: Initialise Terraform
        run: cd terraform && terraform init -reconfigure -backend-config="credentials="${{ steps.auth-gcp.outputs.access_token }}"" && cd ..
          
      - name: Validate Terraform
        run: cd terraform && terraform validate -backend-config="credentials="${{ steps.auth-gcp.outputs.credentials_file_path }}"" && cd ..
      - name: Create infrastructure
        run: cd terraform && terraform apply -backend-config="credentials="${{ steps.auth-gcp.outputs.credentials_file_path }}"" -target=module.self_hosted_ci_runners.google_compute_instance.runner -var 'github_access_token=${ secrets.PERSONAL_ACCESS_TOKEN }' && cd ..
