name: Deploy self-hosted actions runner

on:
  push:
    branches: 
      - main

jobs:
  run:
    name: 'Setup GCP and Deploy self-hosted actions runner'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.TERRAFORM_SERVICE_ACCOUNT_EMAIL }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          token_format: 'access_token'
          access_token_lifetime: '1800' # 30 minutes

      - name: Initialise Terraform
        run: cd terraform && terraform init -backend-config='access_token=${{ steps.auth-gcp.outputs.access_token }}' && cd ..

      - name: Generate Plan
        run: cd terraform && terraform plan -target=module.self_hosted_ci_runners.google_compute_instance.runner && cd ..

      - name: Validate Resources
        run: cd terraform && terraform validate && cd ..

      - name: Create infrastructure
        run: cd terraform && terraform apply -target=module.self_hosted_ci_runners.google_compute_instance.runner && cd ..
